import type { RecipeTheme } from "@/types/recipe";

const themeMap: Record<string, RecipeTheme> = {
  thai: {
    primary: "#C84B31",
    secondary: "#F4A261",
    accent: "#E76F51",
    background: "#FFF8F0",
    text: "#2D1810",
    muted: "#F5E6D8",
    fontFamily: "Georgia, serif",
  },
  italian: {
    primary: "#8B2635",
    secondary: "#D4A373",
    accent: "#588157",
    background: "#FDF6EC",
    text: "#1C110A",
    muted: "#F3E5D2",
    fontFamily: "Georgia, serif",
  },
  japanese: {
    primary: "#1B1F3B",
    secondary: "#C8795C",
    accent: "#8B6F5C",
    background: "#FBF8F4",
    text: "#1A1A2E",
    muted: "#E8E0D5",
    fontFamily: "Georgia, serif",
  },
  indian: {
    primary: "#D43615",
    secondary: "#F7C948",
    accent: "#2E7D32",
    background: "#FFFDF5",
    text: "#1A0D00",
    muted: "#FEF3C7",
    fontFamily: "Georgia, serif",
  },
  mexican: {
    primary: "#9C2E2E",
    secondary: "#E8A838",
    accent: "#3A6B4C",
    background: "#FFF9F0",
    text: "#1C1005",
    muted: "#FDEBD0",
    fontFamily: "Georgia, serif",
  },
  chinese: {
    primary: "#C23B22",
    secondary: "#DAA520",
    accent: "#2F4858",
    background: "#FFFBF5",
    text: "#1C1411",
    muted: "#F5E8D8",
    fontFamily: "Georgia, serif",
  },
  french: {
    primary: "#3D405B",
    secondary: "#C4A882",
    accent: "#81B29A",
    background: "#FDFCF9",
    text: "#1B1B1B",
    muted: "#F0EBE3",
    fontFamily: "Georgia, serif",
  },
  korean: {
    primary: "#C62828",
    secondary: "#FFB74D",
    accent: "#2E5C31",
    background: "#FFFAF5",
    text: "#1A1410",
    muted: "#F5E6D3",
    fontFamily: "Georgia, serif",
  },
  mediterranean: {
    primary: "#1E5A8A",
    secondary: "#E8A840",
    accent: "#4A8C5C",
    background: "#FBFDF9",
    text: "#1A1A2E",
    muted: "#E8EDE8",
    fontFamily: "Georgia, serif",
  },
  american: {
    primary: "#4A4E69",
    secondary: "#C9ADA7",
    accent: "#9A8C98",
    background: "#FDFCFB",
    text: "#1C1C1C",
    muted: "#F2E9E4",
    fontFamily: "Georgia, serif",
  },
  "middle-eastern": {
    primary: "#8B4513",
    secondary: "#D4A76A",
    accent: "#2E7D32",
    background: "#FFFDF8",
    text: "#1C1005",
    muted: "#F5ECD7",
    fontFamily: "Georgia, serif",
  },
  other: {
    primary: "#4A5568",
    secondary: "#A0AEC0",
    accent: "#68D391",
    background: "#FDFCFB",
    text: "#1A202C",
    muted: "#EDF2F7",
    fontFamily: "Georgia, serif",
  },
};

export function getTheme(cuisine: string): RecipeTheme {
  const key = cuisine.toLowerCase().trim();
  return themeMap[key] ?? themeMap.other;
}
