import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_KEY!
);

export async function GET() {
  const results: string[] = [];

  try {
    // 1. Fetch pending requests
    const { data: requests } = await supabase
      .from("recipe_requests")
      .select("*")
      .eq("status", "pending")
      .order("created_at", { ascending: true })
      .limit(5);

    if (!requests || requests.length === 0) {
      return NextResponse.json({ processed: 0 });
    }

    for (const req of requests) {
      try {
        results.push(`Processing: ${req.prompt}`);

        // 2. Generate HTML recipe via DeepSeek
        const htmlResponse = await fetch("https://api.deepseek.com/chat/completions", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${process.env.DEEPSEEK_API_KEY}`,
          },
          body: JSON.stringify({
            model: "deepseek-chat",
            messages: [
              {
                role: "system",
                content: "You are a James Beard award-winning chef and designer. Create a beautiful self-contained HTML recipe page. Include inline CSS (warm palette, Google Fonts), hand-crafted SVGs showing the dish and techniques, sensory writing, cultural context, pro tips, storage guidance. Return ONLY the complete HTML document starting with <!doctype html>. No markdown wrapping.",
              },
              {
                role: "user",
                content: `Create a full HTML recipe for: ${req.prompt}. Include: custom warm CSS with paper textures, Fraunces + Newsreader Google Fonts, hand-crafted SVG of the finished dish, SVG diagrams for key techniques, ingredients with precise amounts, detailed steps with WHY and sensory cues, 3-5 pro tips, storage guidance. Return ONLY the HTML.`,
              },
            ],
            temperature: 0.9,
            max_tokens: 8192,
          }),
        });

        const htmlData = await htmlResponse.json() as { choices?: Array<{ message?: { content?: string } }> };
        const html = htmlData.choices?.[0]?.message?.content ?? "";

        if (!html || html.length < 100) {
          results.push(`  Failed to generate HTML for: ${req.prompt}`);
          continue;
        }

        // 3. Extract metadata
        const metaResponse = await fetch("https://api.deepseek.com/chat/completions", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${process.env.DEEPSEEK_API_KEY}`,
          },
          body: JSON.stringify({
            model: "deepseek-chat",
            messages: [
              { role: "system", content: "Extract recipe metadata from HTML. Return ONLY valid JSON." },
              {
                role: "user",
                content: `Extract: title, description (one sentence), cuisine, category, prepTime (min), cookTime (min), totalTime (min), difficulty, servings (number), tags (array). From this HTML: ${html.slice(0, 6000)}`,
              },
            ],
            temperature: 0.3,
            max_tokens: 1024,
          }),
        });

        const metaText = (metaResponse.json() as any).choices?.[0]?.message?.content ?? "{}";
        const meta = JSON.parse(metaText.replace(/```/g, "").trim());

        // 4. Save to recipes table
        const recipeId = crypto.randomUUID();
        const now = new Date().toISOString();

        await supabase.from("recipes").insert({
          id: recipeId,
          title: meta.title ?? req.prompt,
          description: meta.description ?? "",
          cuisine: meta.cuisine ?? "other",
          category: meta.category ?? "other",
          prep_time: meta.prepTime ?? 0,
          cook_time: meta.cookTime ?? 0,
          total_time: meta.totalTime ?? 0,
          difficulty: meta.difficulty ?? "medium",
          servings: meta.servings ?? 4,
          ingredients: [],
          steps: [],
          equipment: [],
          nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0 },
          tags: meta.tags ?? [],
          version: "home",
          theme: { primary: "#8B2635", secondary: "#D4A373", accent: "#588157", background: "#FDF6EC", text: "#1C110A", muted: "#F3E5D2", fontFamily: "Georgia, serif" },
          svg_illustrations: [],
          html,
          source_notes: "Auto-generated by Vercel cron via DeepSeek",
          created_at: now,
          updated_at: now,
        });

        // 5. Mark request complete
        await supabase
          .from("recipe_requests")
          .update({ status: "completed", recipe_id: recipeId })
          .eq("id", req.id);

        results.push(`  Complete: ${meta.title ?? req.prompt} (${recipeId})`);
      } catch (e) {
        results.push(`  Error: ${req.prompt} - ${e instanceof Error ? e.message : "unknown"}`);
      }
    }

    return NextResponse.json({ processed: requests.length, results });
  } catch (e) {
    return NextResponse.json(
      { error: e instanceof Error ? e.message : "Cron failed" },
      { status: 500 }
    );
  }
}
